# Generated by Django 5.1.3 on 2025-07-01 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_doctorprofile_specialization'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctorprofile',
            name='meeting_link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
