# Generated by Django 5.1.3 on 2025-07-05 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_doctorprofile_meeting_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctorprofile',
            name='specialization',
            field=models.CharField(choices=[('Cardiologist', 'Cardiologist'), ('Dermatologist', 'Dermatologist'), ('Neurologist', 'Neurologist'), ('Pediatrician', 'Pediatrician'), ('Orthopedic', 'Orthopedic'), ('Gynecologist', 'Gynecologist'), ('General Physician', 'General Physician'), ('ENT Specialist', 'ENT Specialist')], max_length=100),
        ),
    ]
