# Generated by Django 5.1.3 on 2025-07-20 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_patientprofile_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctorprofile',
            name='qualification',
            field=models.CharField(default='MBBS', max_length=200),
        ),
    ]
