# Generated by Django 5.1.3 on 2025-09-05 15:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0008_doctorprofile_qualification"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="user_type",
            field=models.CharField(
                choices=[
                    ("doctor", "Doctor"),
                    ("patient", "Patient"),
                    ("lab", "Lab Staff"),
                ],
                default="patient",
                max_length=10,
            ),
        ),
        migrations.CreateModel(
            name="LabProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "lab_name",
                    models.CharField(
                        choices=[
                            ("City Lab", "City Lab"),
                            ("Shifa Diagnostics", "Shifa Diagnostics"),
                            ("Excel Lab", "Excel Lab"),
                        ],
                        max_length=100,
                    ),
                ),
                ("address", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
