# Generated by Django 5.1.3 on 2025-09-06 06:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0009_alter_user_user_type_labprofile"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="labprofile",
            name="address",
        ),
    ]
