# Generated by Django 5.1.3 on 2025-09-09 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0012_alter_labprofile_lab_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="labprofile",
            name="lab_name",
            field=models.CharField(
                choices=[
                    ("city lab", "city lab"),
                    ("shifa diagnostics", "shifa diagnostics"),
                    ("excel lab", "excel lab"),
                ],
                max_length=100,
            ),
        ),
    ]
