# Generated by Django 5.1.3 on 2025-09-13 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0013_alter_labprofile_lab_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="labprofile",
            name="lab_name",
            field=models.CharField(max_length=100),
        ),
    ]
