# Generated by Django 5.1.3 on 2025-09-29 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0014_alter_labprofile_lab_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="doctorprofile",
            name="qualification",
            field=models.CharField(default="", max_length=200),
        ),
    ]
