# Generated by Django 5.1.3 on 2025-09-29 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0015_alter_doctorprofile_qualification"),
    ]

    operations = [
        migrations.AlterField(
            model_name="doctorprofile",
            name="qualification",
            field=models.CharField(default="MBBS", max_length=200),
        ),
    ]
