# Generated by Django 5.1.3 on 2025-06-29 10:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0002_doctor_hospital_doctor_rating_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Doctor',
        ),
    ]
