# Generated by Django 5.1.3 on 2025-07-08 17:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_doctorprofile_specialization'),
        ('appointments', '0008_alter_notification_recipient_delete_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='LabTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('suggested_date', models.DateField(auto_now_add=True)),
                ('is_completed', models.BooleanField(default=False)),
                ('report_file', models.FileField(blank=True, null=True, upload_to='lab_reports/')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.doctorprofile')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lab_tests', to='accounts.patientprofile')),
            ],
        ),
    ]
