# Generated by Django 5.1.3 on 2025-07-08 18:04

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_doctorprofile_specialization'),
        ('appointments', '0009_labtest'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='labtest',
            name='is_completed',
        ),
        migrations.RemoveField(
            model_name='labtest',
            name='suggested_date',
        ),
        migrations.AddField(
            model_name='labtest',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2025, 7, 8, 18, 4, 37, 466967, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='labtest',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Completed', 'Completed')], default='Pending', max_length=50),
        ),
        migrations.AlterField(
            model_name='labtest',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='labtest',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.patientprofile'),
        ),
        migrations.AlterField(
            model_name='labtest',
            name='test_name',
            field=models.CharField(max_length=255),
        ),
    ]
