# Generated by Django 5.1.3 on 2025-07-09 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0010_remove_labtest_is_completed_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='labtest',
            name='lab_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
