# Generated by Django 5.1.3 on 2025-07-09 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0011_labtest_lab_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='labtest',
            name='lab_name',
            field=models.CharField(blank=True, choices=[('City Lab', 'City Lab'), ('Shifa Diagnostics', 'Shifa Diagnostics'), ('Excel Lab', 'Excel Lab')], max_length=255, null=True),
        ),
    ]
