# Generated by Django 5.1.3 on 2025-07-14 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0013_appointment_prescription'),
    ]

    operations = [
        migrations.AddField(
            model_name='labtest',
            name='sample_collection_address',
            field=models.TextField(blank=True, null=True),
        ),
    ]
