# Generated by Django 5.1.3 on 2025-07-17 16:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_patientprofile_address'),
        ('appointments', '0014_labtest_sample_collection_address'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='labtest',
            options={'ordering': ['-created_at'], 'verbose_name': 'Laboratory Test', 'verbose_name_plural': 'Laboratory Tests'},
        ),
        migrations.AddField(
            model_name='labtest',
            name='completed_at',
            field=models.DateTimeField(blank=True, help_text='When the test was marked as completed', null=True),
        ),
        migrations.AddField(
            model_name='labtest',
            name='priority',
            field=models.CharField(choices=[('Routine', 'Routine (within 3 days)'), ('Urgent', 'Urgent (within 24 hours)'), ('STAT', 'STAT (immediate)')], default='Routine', help_text='How quickly the test needs to be performed', max_length=10),
        ),
        migrations.AddField(
            model_name='labtest',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='When the test record was last updated'),
        ),
        migrations.AlterField(
            model_name='labtest',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='When the test was initially suggested'),
        ),
        migrations.AlterField(
            model_name='labtest',
            name='description',
            field=models.TextField(blank=True, help_text="Doctor's notes or special instructions for the test", null=True),
        ),
        migrations.AlterField(
            model_name='labtest',
            name='doctor',
            field=models.ForeignKey(help_text='Doctor who ordered this test', on_delete=django.db.models.deletion.CASCADE, related_name='ordered_tests', to='accounts.doctorprofile'),
        ),
        migrations.AlterField(
            model_name='labtest',
            name='lab_name',
            field=models.CharField(blank=True, choices=[('City Lab', 'City Lab'), ('Shifa Diagnostics', 'Shifa Diagnostics'), ('Excel Lab', 'Excel Lab')], help_text='Laboratory facility where test will be conducted', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='labtest',
            name='patient',
            field=models.ForeignKey(help_text='Patient who needs this test', on_delete=django.db.models.deletion.CASCADE, related_name='lab_tests', to='accounts.patientprofile'),
        ),
        migrations.AlterField(
            model_name='labtest',
            name='report_file',
            field=models.FileField(blank=True, help_text='Uploaded lab test results/report', null=True, upload_to='lab_reports/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='labtest',
            name='sample_collection_address',
            field=models.TextField(blank=True, help_text='Complete address for sample collection', null=True),
        ),
        migrations.AlterField(
            model_name='labtest',
            name='status',
            field=models.CharField(choices=[('Suggested', 'Suggested by Doctor'), ('Details Pending', 'Patient Details Needed'), ('Sent to Lab', 'Sent to Laboratory'), ('Sample Collected', 'Sample Collected'), ('In Progress', 'Test in Progress'), ('Completed', 'Test Completed'), ('Cancelled', 'Test Cancelled')], default='Suggested', help_text='Current status of the test in the workflow', max_length=20),
        ),
        migrations.AlterField(
            model_name='labtest',
            name='test_name',
            field=models.CharField(help_text='Name of the laboratory test to be performed', max_length=255),
        ),
    ]
