# Generated by Django 5.1.3 on 2025-07-18 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0016_remove_labtest_description_remove_labtest_priority'),
    ]

    operations = [
        migrations.AlterField(
            model_name='labtest',
            name='report_file',
            field=models.FileField(blank=True, null=True, upload_to='lab_reports/'),
        ),
    ]
