# Generated by Django 5.1.3 on 2025-07-25 16:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("appointments", "0019_prescription"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="appointment",
            options={},
        ),
        migrations.RenameField(
            model_name="appointment",
            old_name="zoom_join_url",
            new_name="jitsi_meeting_url",
        ),
        migrations.RemoveField(
            model_name="appointment",
            name="zoom_meeting_id",
        ),
    ]
