# Generated by Django 5.1.3 on 2025-07-26 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("appointments", "0020_alter_appointment_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="appointment",
            options={"ordering": ["date", "start_time"]},
        ),
        migrations.RenameField(
            model_name="appointment",
            old_name="jitsi_meeting_url",
            new_name="zoom_join_url",
        ),
        migrations.AddField(
            model_name="appointment",
            name="zoom_meeting_id",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
