# Generated by Django 5.1.3 on 2025-07-29 07:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("appointments", "0021_alter_appointment_options_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="appointment",
            name="zoom_join_url",
        ),
        migrations.RemoveField(
            model_name="appointment",
            name="zoom_meeting_id",
        ),
    ]
