# Generated by Django 5.1.3 on 2025-07-30 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("appointments", "0022_remove_appointment_zoom_join_url_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="appointment",
            name="google_meet_link",
            field=models.URLField(blank=True, null=True),
        ),
    ]
