# Generated by Django 5.1.3 on 2025-07-31 11:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("appointments", "0023_appointment_google_meet_link"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="appointment",
            name="google_meet_link",
        ),
    ]
