# Generated by Django 5.1.3 on 2025-08-28 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("appointments", "0025_alter_appointment_status"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="appointment",
            name="reason",
        ),
        migrations.AddField(
            model_name="appointment",
            name="transaction_id",
            field=models.CharField(blank=True, max_length=11, null=True),
        ),
    ]
