# Generated by Django 5.1.3 on 2025-09-05 15:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0009_alter_user_user_type_labprofile"),
        ("appointments", "0026_remove_appointment_reason_appointment_transaction_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="labtest",
            name="lab",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="lab_tests",
                to="accounts.labprofile",
            ),
        ),
    ]
