# Generated by Django 5.1.3 on 2025-09-09 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("appointments", "0027_labtest_lab"),
    ]

    operations = [
        migrations.AlterField(
            model_name="labtest",
            name="lab_name",
            field=models.CharField(
                blank=True,
                choices=[
                    ("city Lab", "city Lab"),
                    ("shifa diagnostics", "shifa diagnostics"),
                    ("excel Lab", "excel Lab"),
                ],
                help_text="Laboratory facility where test will be conducted",
                max_length=255,
                null=True,
            ),
        ),
    ]
