# Generated by Django 5.1.3 on 2025-09-11 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("appointments", "0030_alter_labtest_lab_name"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="labtest",
            name="lab_name",
        ),
        migrations.AddField(
            model_name="labtest",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="labtest",
            name="completed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="labtest",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="labtest",
            name="sample_collection_address",
            field=models.TextField(
                blank=True, help_text="Patient address for sample collection", null=True
            ),
        ),
        migrations.AlterField(
            model_name="labtest",
            name="status",
            field=models.CharField(
                choices=[
                    ("Suggested", "Suggested by Doctor"),
                    ("Details Pending", "Patient Details Needed"),
                    ("Sent to Lab", "Sent to Laboratory"),
                    ("Sample Collected", "Sample Collected"),
                    ("In Progress", "Test in Progress"),
                    ("Completed", "Test Completed"),
                    ("Cancelled", "Test Cancelled"),
                ],
                default="Suggested",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="labtest",
            name="test_name",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="labtest",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
