# Generated by Django 5.1.3 on 2025-09-12 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("appointments", "0032_alter_labtest_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="labtest",
            name="status",
            field=models.CharField(
                choices=[
                    ("Suggested", "Suggested by Doctor"),
                    ("Details Pending", "Patient Details Needed"),
                    ("Sent to Lab", "Sent to Laboratory"),
                    ("Sample Collected", "Sample Collected"),
                    ("In Progress", "Test in Progress"),
                    ("Completed", "Test Completed"),
                    ("Cancelled", "Test Cancelled"),
                    ("Pending", "Pending"),
                ],
                default="Suggested",
                max_length=20,
            ),
        ),
    ]
